### ISSUE TITLE
Can these example work on SEEED XIAO ESP32S3, Also any example of LE audio i2s stream

### ISSUE THREAD

**Issue by gauravacad** [luminationlabs/Sonatino-Examples#1]
We are searching for A2dp Alternate for new esp32s3 boards
We have find this place but codes are few.
any Idea or lead you can provide

**Comment by lumination-labs** [comment]
These examples have pin configurations that are specific to Sonatino, and probably won't work with other boards without modification.

LE Audio requires at least Bluetooth 5.2, so unfortunately no ESP32-S3 devices (which use Bluetooth 5.0) will support LE Audio.

**Comment by gauravacad** [comment]
Thanks for the email
I find the note useful
Please tell me it is possible with esp32s3 seed Xiao can use i2s full
duplex. Like inmp441 as digital microphone and external dac as output.
