### ISSUE TITLE
Trouble using I2S from arduino-audio-tools lib

### ISSUE THREAD

**Issue by rkeniger** [luminationlabs/Sonatino-Examples#3]
I'm trying to get the [arduino-audio-tools](https://github.com/pschatzmann/arduino-audio-tools) library working with the Sonatino as it's considerably more sophisticated than the `esp8266audio` library used in the examples.

I've configured the I2S pins correctly as far as I can tell, but I get no output.

The `I2SStream` class can take a mute pin in its initializer and I've tried setting that to `14` with no success (i.e. `I2SStream i2s(14);`.

I've also tried manually using `pinMode(14, OUTPUT);  digitalWrite(14, HIGH);` to ensure the DAC is not muted after the `dec.begin();` call.

I recognize that this could be a library problem but this library works with pretty much every other board out there so I'm surprised it doesn't work.

```
#include "AudioTools.h"
#include "AudioCodecs/CodecMP3Helix.h"

URLStream url("Rainbow Connection","greenfrog69");
I2SStream i2s; // final output of decoded stream
MP3DecoderHelix codec;
EncodedAudioStream dec(&i2s, &codec); // Decoding stream
StreamCopy copier(dec, url); // copy url to decoder

void setup(){
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);  

  // setup i2s
  auto config = i2s.defaultConfig(TX_MODE);
  config.buffer_size = 1024;
  config.i2s_format = I2S_STD_FORMAT;
  
  // these pins seem to match the Sonatino board specs
  config.pin_bck = 15;
  config.pin_ws = 16;
  config.pin_data = 17;
  
  i2s.begin(config);

  // setup I2S based on sampling rate provided by decoder
  dec.begin();

// mp3 radio
  url.begin("http://stream.srg-ssr.ch/m/rsj/mp3_128","audio/mp3");

}

void loop(){
  copier.copy();
}
```

**Comment by lumination-labs** [comment]
I haven't used that library before, but you might want to try adding `config.pin_mck = 0;` in your pin configuration.

Some DACs don't require a master clock signal, which I guess is why some libraries disable it by default (arduino-audio-tools might be one of those). The DAC and ADC on Sonatino need it in order to operate.

If that doesn't help, let me know and I'll do my best to reproduce the issue and figure it out.

**Comment by rkeniger** [comment]
@lumination-labs thank you - that was it! Works perfectly.
